### ISSUE TITLE
ODS F Score metric 

### ISSUE THREAD

**Issue by Arka161** [iocak28/UNet_edge_detection#1]
Hello, 

This is not an issue, but a simple doubt in the methodology. 
I read your report, and it mentions the ODS and OIS F-Scores for UNET are somewhere around 0.7. I have tried running your notebooks, and I've tried running Canny, and other algorithms on my end, but I get an F-Score far less than 0.5 in most cases. 
Your Notebook also states the following scores: 

![image](https://user-images.githubusercontent.com/20723780/131270629-bd8875af-22e2-47a5-a52f-193fda19bde8.png)

But, your paper (report) states this: 

![image](https://user-images.githubusercontent.com/20723780/131270656-a7348bf1-6f71-4e9a-93f1-d9518319f248.png)

I am just trying to understand the difference in the metrics, so I can re-implement them for my use-cases whenever needed. 
Thank you

**Comment by Arka161** [comment]
Also, I notice that the mAP is also lower than the actual values mentioned in the figure in the paper (PDF). I was trying to understand if there is any difference in the scales.

**Comment by iocak28** [comment]
Hi, we used the evaluation methodology and codes in the original dataset repository. Please refer to here for further information: https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/resources.html
